title: ENGL 340 Spring 2024
description: ENGL 340 Spring 2024 at SUNY Geneseo
theme: just-the-docs

url: https://paulschacht.net/engl340-s24

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts:
  warning:
    title: Be Careful
    color: red
  tip:
    title: Tip
    color: green
  alt-warning:
    color: red
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: purple