title: Literature and Literary Study in the Digital Age
description: ENGL 340 Spring 2024 at SUNY Geneseo
theme: just-the-docs

url: https://paulschacht.net/engl340-s24

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
